In [16]:
from tensorflow.keras.preprocessing.text import one_hot

In [17]:
#example of converting word to vector using hot
sent=[  'the glass of milk',
     'the glass of juice',
     'the cup of tea',
    'I am a good boy',
     'I am a good developer',
     'understand the meaning of words',
     'your videos are good',]

## Define the vocabulary size
voc_size=10000

### One Hot Representation
one_hot_repr=[one_hot(words,voc_size)for words in sent]
one_hot_repr

[[4648, 6570, 6499, 8697],
 [4648, 6570, 6499, 273],
 [4648, 4128, 6499, 2547],
 [691, 1809, 3158, 4668, 5401],
 [691, 1809, 3158, 4668, 9560],
 [9401, 4648, 2411, 6499, 5702],
 [6227, 468, 9950, 4668]]

In [18]:
##word embedding representation
from tensorflow.keras.layers import Embedding
from tensorflow.keras.utils import pad_sequences
from tensorflow.keras.models import Sequential 

In [19]:
import numpy as np

In [20]:
sent_length=8
embedded_docs=pad_sequences(one_hot_repr, padding='pre',maxlen=sent_length)
print(embedded_docs)

#########################OR##################################################
print("\nOR\n")
embedded_docs=pad_sequences(one_hot_repr, padding='post',maxlen=sent_length)
print(embedded_docs)

[[   0    0    0    0 4648 6570 6499 8697]
 [   0    0    0    0 4648 6570 6499  273]
 [   0    0    0    0 4648 4128 6499 2547]
 [   0    0    0  691 1809 3158 4668 5401]
 [   0    0    0  691 1809 3158 4668 9560]
 [   0    0    0 9401 4648 2411 6499 5702]
 [   0    0    0    0 6227  468 9950 4668]]

OR

[[4648 6570 6499 8697    0    0    0    0]
 [4648 6570 6499  273    0    0    0    0]
 [4648 4128 6499 2547    0    0    0    0]
 [ 691 1809 3158 4668 5401    0    0    0]
 [ 691 1809 3158 4668 9560    0    0    0]
 [9401 4648 2411 6499 5702    0    0    0]
 [6227  468 9950 4668    0    0    0    0]]


In [21]:
#Feature Representation
dim=10

In [25]:
model=Sequential()
model.add(Embedding(voc_size,dim,input_length=sent_length))
model.build(input_shape=(None, sent_length))
model.compile('adam','mse')

In [26]:
model.summary()

Model: "sequential_2"

┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━┓
┃ Layer (type)                    ┃ Output Shape           ┃       Param # ┃
┡━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━┩
│ embedding_2 (Embedding)         │ (None, 8, 10)          │       100,000 │
└─────────────────────────────────┴────────────────────────┴───────────────┘

 Total params: 100,000 (390.62 KB)

 Trainable params: 100,000 (390.62 KB)

 Non-trainable params: 0 (0.00 B)

In [27]:
model.predict(embedded_docs)

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 190ms/step


array([[[-5.5741146e-04,  3.3728767e-02,  1.6299497e-02, -1.3412226e-02,
         -1.8461168e-02, -6.6631921e-03,  4.7163967e-02, -2.1435166e-02,
         -4.4895172e-02, -4.9579740e-02],
        [-2.4848808e-02,  4.5739636e-03,  1.0804512e-02, -7.8056343e-03,
          4.5934703e-02,  2.5611009e-02, -4.3881416e-02, -2.9877663e-02,
          7.0956238e-03, -4.1097380e-02],
        [-3.2852173e-02,  4.2518150e-02,  1.3680566e-02, -1.4816843e-02,
          1.7182101e-02,  3.8694255e-03, -6.5933242e-03, -4.7798336e-02,
          4.4396076e-02, -3.3293165e-02],
        [ 2.8092377e-03, -2.1756494e-02, -4.7938444e-02, -3.7145030e-02,
          2.0834710e-02,  4.3612745e-02,  1.4002595e-02, -4.5692503e-02,
         -3.7063122e-02, -1.9130303e-02],
        [ 6.8122037e-03,  3.9263774e-02, -4.5389522e-02, -8.2931891e-03,
         -3.3268500e-02,  1.0694504e-02, -3.1210721e-02,  2.0063702e-02,
          1.4201652e-02,  1.9467164e-02],
        [ 6.8122037e-03,  3.9263774e-02, -4.5389522e-02, -8.

In [28]:
embedded_docs[0]

array([4648, 6570, 6499, 8697,    0,    0,    0,    0])